DlTEXTS = {
        goToday : "Go Today",

        _date_monthNames : [ "January",
			     "February",
			     "March",
			     "April",
			     "May",
			     "June",
			     "July",
			     "August",
			     "September",
			     "October",
			     "November",
			     "December" ],

        _date_shortMonthNames : [ "Jan",
			          "Feb",
			          "Mar",
			          "Apr",
			          "May",
			          "Jun",
			          "Jul",
			          "Aug",
			          "Sep",
			          "Oct",
			          "Nov",
			          "Dec" ],

        _date_dayNames : [ "Sunday",
		           "Monday",
		           "Tuesday",
		           "Wednesday",
		           "Thursday",
		           "Friday",
		           "Saturday",
		           "Sunday" ],

        _date_shortDayNames : [ "Su",
			        "Mo",
			        "Tu",
			        "We",
			        "Th",
			        "Fr",
			        "Sa",
			        "Su" ],

        _date_firstDayOfWeek : 1    // 0 is Sunday
};
